### ISSUE TITLE
[Bug] StoryBook chapter number displayed incorrectly

### ISSUE THREAD

**Issue by Keerthi4308** [elimu-ai/webapp#1092]
At http://eng.elimu.ai/content/storybook/edit/66 there seems to be a bug with the way a storybook's chapter number is calculated: It shows "Chapter 14/13" instead of "13/13".
<img width="364" alt="Screen Shot 2020-11-10 at 1 35 32 PM" src="https://user-images.githubusercontent.com/19628734/98687227-58c18280-231e-11eb-9b33-38d26714d452.png">

**Comment by nya-elimuai** [comment]
This is what the database looks like for this storybook's chapters: 

```
> SELECT * FROM StoryBookChapter WHERE storyBook_id = 66;
+-----+-----------+--------------+----------+
| id  | sortOrder | storyBook_id | image_id |
+-----+-----------+--------------+----------+
| 147 |         1 |           66 |      495 |
| 148 |         2 |           66 |      496 |
| 149 |         3 |           66 |      497 |
| 150 |         4 |           66 |      498 |
| 151 |         5 |           66 |      499 |
| 152 |         6 |           66 |      500 |
| 153 |         7 |           66 |      501 |
| 154 |         8 |           66 |      502 |
| 155 |         9 |           66 |      503 |
| 156 |        10 |           66 |      504 |
| 157 |        11 |           66 |      505 |
| 158 |        12 |           66 |      506 |
| 159 |        13 |           66 |      507 |
+-----+-----------+--------------+----------+
13 rows in set (0.00 sec)
```

The `sortOrder` is supposed to start at zero: https://github.com/elimu-ai/webapp/blob/master/src/main/java/ai/elimu/model/content/StoryBookChapter.java#L16

So something might have gone wrong when setting the `sortOrder` values during the import of the ePUB file.

**Comment by nya-elimuai** [comment]
The Hindi version of the same storybook does not have the same problem: http://hin.test.elimu.ai/content/storybook/edit/39

<img width="315" alt="Screen Shot 2020-11-12 at 12 43 27 AM" src="https://user-images.githubusercontent.com/15718174/98877151-7ca0d780-2488-11eb-919d-39510473cffe.png">

# 🤔

**Comment by nya-elimuai** [comment]
Here is another book (Hindi) with the same bug: http://hin.test.elimu.ai/content/storybook/edit/26

<img width="263" alt="Screen Shot 2020-11-12 at 12 49 40 AM" src="https://user-images.githubusercontent.com/15718174/98877527-60ea0100-2489-11eb-91b9-cc60a329af14.png">

**Comment by Keerthi4308** [comment]
Interesting.. thanks for sharing them @nya-elimuai I'm taking a look now.

**Comment by nya-elimuai** [comment]
Note that the ePUB importer automatically removes storybook chapters that are not needed (book metadata): https://github.com/elimu-ai/webapp/blob/master/src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java#L364

This might have a negative effect, on how the `sortOrder` is given for each chapter.

**Comment by Keerthi4308** [comment]
@nya-elimuai You are right the epub file for this storyBook has MetaData http://eng.elimu.ai/content/storybook/edit/66  which maps to Chapter with sortOrder = 0.  As a result chapter with actual content has sortOrder 1 and we are adding sortOrder+1 while storing in DB. I observed that  StoryBook start with Chapter 2/13 instead of 1/13 which leads to 14/13 with all the example storybooks you shared in the above comment sec. 

Couple of options I can think of:
1. **Handle while we extract Pragrapgh from chapte**r itself  based on if the paragraph contains metadata or not([Code ref](https://github.com/elimu-ai/webapp/blob/1c75e7aa192ce6af09604d2b592667d8e0e7f835/src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java#L289)) . That is either skip adding storeBookChapter altogether to storyBookChapters and it's corresponding pragraphs or manipulate the sortOrder for this chapter to be -1 and maintain a counter for other chapters sortOrder instead of  `storyBookChapter.setSortOrder(storyBookChapters.size());`

2.  Maintain  a counter for occurence of metaData and **reset the sortOrder for every other StoryBookChapter**  just before storing in the DB as sortOrder- (occurence of metadata) . That is after this code logic.([Code ref](https://github.com/elimu-ai/webapp/blob/1c75e7aa192ce6af09604d2b592667d8e0e7f835/src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java#L364)). 
Ex: Chapter 0 has MetaData => metaDataCounter=1
And for next Chapter 1  with sortOrder =1 =>  sortOrder= sortOrder- metaDataCounter => 0
Chapter 2 has MetaData => metaDataCounter=2
And for next Chapter 3  with sortOrder =3 =>  sortOrder= sortOrder- metaDataCounter => 1

I more leaned towards option 1 just that we can handle it upfront if we aren't using it anyway.  Let me know your thoughts and whether you see any issues/concerns.

**Comment by Keerthi4308** [comment]
Apart from that I'm curious why are we receiving this sort of metaData only for some StoryBooks and not others because metadata info like author/illustrator/translator could infact be useful right, correct me if we are reciving this through other some means.

**Comment by nya-elimuai** [comment]
> I more leaned towards option 1 just that we can handle it upfront if we aren't using it anyway. Let me know your thoughts and whether you see any issues/concerns.

@Keerthi4308 Thank you for tracking down the bug, and for suggesting how to solve it 👍

I have not looked at the details yet, so I'm not able to suggest the better of the two options. If you are leaning towards option 1, feel free to attempt an implementation of the bug. And let me know if I can assist.

**Comment by nya-elimuai** [comment]
> Apart from that, I'm curious why are we receiving this sort of metaData only for some StoryBooks and not others because metadata info like author/illustrator/translator could infact be useful right, correct me if we are receiving this through some other means.

@Keerthi4308 Part of the challenge is that ePUB files come from various sources, and they are all formatted differently. Currently we have one ePUB importer, and it works for StoryWeaver, Global Digital Library and Let's Read.

Every time a contributor imports an ePUB, she stores an attribution URL and the book's license so that we can keep track of this. Currently, this is done manually.
