### ISSUE TITLE
Request e-mail during GitHub authentication

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#1126]
See https://stackoverflow.com/a/35387123

---

- Relates to #699 
- Relates to #1270
- Relates to #1561

**Comment by tomaszsmy** [comment]
https://github.com/elimu-ai/webapp/pull/1604

**Comment by nya-elimuai** [comment]
https://app.dework.xyz/elimuai/web-development?taskId=d7d90275-9c1b-41e3-a210-d549a39949d3
