### ISSUE TITLE
Word is duplicated when text changed to another value

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#1169]
Editing a word's text does not work properly.

<img width="290" alt="Screen Shot 2020-12-14 at 5 40 54 PM" src="https://user-images.githubusercontent.com/15718174/102108733-f1768100-3e3b-11eb-9122-920933907c33.png">

**Comment by gg-dev-05** [comment]
May I work on this issue?

**Comment by nya-elimuai** [comment]
> May I work on this issue?

@gg-dev-05 Yes, please 🙂

Do you need any help to [get started](https://github.com/elimu-ai/wiki/blob/master/CONTRIBUTING.md) with your contribution?

**Comment by gg-dev-05** [comment]
Thanks @nya-elimuai . I will try my best to work on this. Please assign me to this issue 😃

**Comment by nya-elimuai** [comment]
> Thanks @nya-elimuai . I will try my best to work on this. Please assign me to this issue 😃

I've sent you an invite to join the GitHub organization. So you should now have access to assign yourself to the issue, and move the card into the "In progress" column at https://github.com/elimu-ai/webapp/projects/6#card-51099874

**Comment by gg-dev-05** [comment]
@nya-elimuai, can you mention the steps to re-create this bug.

**Comment by nya-elimuai** [comment]
> can you mention the steps to re-create this bug.

@gg-dev-05 I just tested, and was not able to reproduce the bug. So it seems we can ignore this issue, my apologies for not double-checking this when creating it. So I'm closing this.

By the way, it would be great if you pick issues that are located at the top of the "To do" list, because they have higher priority. Maybe you would be interested in implementing #1166?: https://github.com/elimu-ai/webapp/projects/6#card-50909305

**Comment by nya-elimuai** [comment]
This issue was originally created due to a bug report about the word "umntu"/"umtu" at http://xho.elimu.ai/content/word/list being duplicated when edited. But we were not able to reproduce the bug.
