### ISSUE TITLE
Do not allow Emojis with Unicode version larger than 9.0

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#1171]
See https://github.com/elimu-ai/webapp/blob/master/src/main/java/ai/elimu/model/content/Emoji.java

Make it impossible to add an emoji with Unicode version > 9.0.

This restriction will make us sure that emojis will appear on devices running Android OS versions as old as [7.0 (API 24)](https://github.com/elimu-ai/appstore/blob/master/README.md#what-devices-are-being-used), instead of being displayed as an empty square on older devices.

<img width="628" alt="Screen Shot 2020-12-26 at 9 11 33 PM" src="https://user-images.githubusercontent.com/15718174/103158508-52e90900-47c7-11eb-87fe-b21309294879.png">

**Comment by nya-elimuai** [comment]
@gg-dev-05 This might be a good first issue for you?

**Comment by gg-dev-05** [comment]
Sure, I will work on this!!

**Comment by nya-elimuai** [comment]
> Sure, I will work on this!!

@gg-dev-05 Great, thank you 🙂

And if you need any help, you can also reach us in Slack: https://join.slack.com/t/elimu-ai/shared_invite/zt-eoc921ow-0cfjATlIF2X~zHhSgSyaAw

**Comment by gg-dev-05** [comment]
@nya-elimuai , I can't seem to figure out what to do here. Please assign this issue to someone else.

**Comment by nya-elimuai** [comment]
@gg-dev-05 Okay. Would you like to try working on another task?

**Comment by gg-dev-05** [comment]
Yes, I am willing to work on other tasks but I do not know much of java.

**Comment by cebr76** [comment]
Hey, am I right about this issue still being unassigned? :) 
I would like to work on it as my first issue

**Comment by nya-elimuai** [comment]
@cebr76 Yes, that's right. You are welcome to give it a try 🙂

**Comment by nya-elimuai** [comment]
@cebr76 Also see https://github.com/elimu-ai/wiki/blob/master/CONTRIBUTING.md and https://github.com/elimu-ai/webapp/blob/master/INSTALL.md

**Comment by cebr76** [comment]
Thank you :) I managed to setup the project and I think I could also reproduce the issue. I was a little confused about those three input fields though 😅
Do I need to check the unicode version entered by the user or the actual unicode version of the "glyph"?
And what response/error message do you expect the user to recieve when trying to submit a higher number?

**Comment by nya-elimuai** [comment]
> Do I need to check the unicode version entered by the user or the actual unicode version of the "glyph"?

@cebr76 Is it possible to automatically extract the unicode version of a glyph? If so, we could simply remove that input field from the form, right?

**Comment by nya-elimuai** [comment]
> And what response/error message do you expect the user to recieve when trying to submit a higher number?

@cebr76 In terms of error messages, we could add something similar to what already exists in https://github.com/elimu-ai/webapp/blob/master/src/main/webapp/WEB-INF/i18n/errors_en.properties

**Comment by cebr76** [comment]
I couldn't find any "easy" way to extract a glyphs unicode version, unfortunately... I thought of a way to solve this by using an enum for supported emojis, but I'm not entirely happy with it and someone would have to update this whenever the allowed unicode version changes.... Should I try this approach anyway (and remove the unicode version input), or just create a pull request for what I've done so far?

**Comment by nya-elimuai** [comment]
> I couldn't find any "easy" way to extract a glyphs unicode version, unfortunately... I thought of a way to solve this by using an enum for supported emojis, but I'm not entirely happy with it and someone would have to update this whenever the allowed unicode version changes.... Should I try this approach anyway (and remove the unicode version input), or just create a pull request for what I've done so far?

@cebr76 Let's keep the code as simple as possible. So I suggest you create a pull request for your current branch, and then add me as a reviewer 🙂

**Comment by cebr76** [comment]
Hey, Sorry for not responding, I had some struggles with another project for university... Anyway, I updated my pull request now :)

**Comment by nya-elimuai** [comment]
@cebr76 For us to reward you for your contribution with [elimu.ai Community Tokens](http://eng.elimu.ai/contributions/aragon-dao), could you send us your Ethereum address?
