### ISSUE TITLE
Make it possible to create multiple words with the same text

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/webapp#1175]
Currently, it is not possible to add a word if another word with the same `text` value already exists in the database.

Change this, to make it possible to add another word with an identical text value, but different meaning/pronunciation. 

For example, the English word "can" can be both a verb and a noun. Refactor the code, to make it possible to store both.

**Comment by tomaszsmy** [comment]
https://github.com/elimu-ai/webapp/pull/1582
Now can be added the same word but with other word type  please check if I haven't missed any place in application.
