### ISSUE TITLE
Configure Jetty server to use SSL certificate

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#1288]
https://www.eclipse.org/jetty/documentation/jetty-9/index.html#configuring-ssl

- [x] `TEST`
- [x] `PROD`

**Comment by jo-elimu** [comment]
Documented procedure in Google Drive: https://drive.google.com/drive/folders/1HQQT5ig7iuy1suqOnw_gDjfHkUMeKawn
