### ISSUE TITLE
Upgrade jQuery to the latest version

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#1341]
https://jquery.com/download/

**Comment by Shubham-Vishwakarma** [comment]
@nya-elimuai 
Please review https://github.com/elimu-ai/webapp/pull/1395

Let me know if any suggestion

**Comment by nya-elimuai** [comment]
@Shubham-Vishwakarma Your $ELIMU 💎 token rewards: https://etherscan.io/tx/0x3fc9bcf7cd34bb2339893ae609bb9aa34a0526c932d18072da9a02f925e5cc0f
