### ISSUE TITLE
Upgrade Chart.js to the latest version

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/webapp#1350]
See https://www.chartjs.org/ and https://github.com/chartjs/Chart.js/releases

**Comment by Shubham-Vishwakarma** [comment]
Where can find https://github.com/elimu-ai/webapp/blob/master/src/main/webapp/static/css/chart.min-2.8.0.css for new version??
On Documentation I can only see chart.min.js https://www.jsdelivr.com/package/npm/chart.js

**Comment by nya-elimuai** [comment]
> Where can find https://github.com/elimu-ai/webapp/blob/master/src/main/webapp/static/css/chart.min-2.8.0.css for new version??
> On Documentation I can only see chart.min.js https://www.jsdelivr.com/package/npm/chart.js

That's a good question. I don't know how we are meant to import the CSS for version 3.x of the library.

Maybe they changed the way CSS/styling is done when moving from version 2.x? There might be some clues in their migration guides: https://github.com/chartjs/Chart.js/releases/tag/v3.0.0
