### ISSUE TITLE
Increase length of word contribution event comment

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#1366]
Increase length of the `comment` property from 255 to 1000 characters in https://github.com/elimu-ai/webapp/blob/master/src/main/java/ai/elimu/model/contributor/WordContributionEvent.java#L26

---

- Relates to https://github.com/elimu-ai/webapp/issues/1319

**Comment by arvind-1** [comment]
@nya-elimuai Can i work on this?

**Comment by nya-elimuai** [comment]
> @nya-elimuai Can i work on this?

@arvind-1 Yes, you are welcome to help 🙂

Do you need some assistance to get started?

**Comment by arvind-1** [comment]
@nya-elimuai Thank you.Yes, that would be great! i will follow through the instructions to run locally. I will ping you if i face any issue in that.

**Comment by nya-elimuai** [comment]
@arvind-1 Your $ELIMU 💎 token rewards: https://etherscan.io/tx/0x3fc9bcf7cd34bb2339893ae609bb9aa34a0526c932d18072da9a02f925e5cc0f
