### ISSUE TITLE
Increase length of WordPeerReviewEvent comment

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#1370]

**Comment by Shubham-Vishwakarma** [comment]
Is this similar to changes made in https://github.com/elimu-ai/webapp/pull/1367

**Comment by nya-elimuai** [comment]
> Is this similar to changes made in #1367

Yes, it is the same type of code refactoring.

**Comment by Shubham-Vishwakarma** [comment]
Done https://github.com/elimu-ai/webapp/pull/1415

**Comment by jo-elimuai** [comment]
@Shubham-Vishwakarma Your $ELIMU 💎 token rewards: https://etherscan.io/tx/0x3fc9bcf7cd34bb2339893ae609bb9aa34a0526c932d18072da9a02f925e5cc0f

**Comment by nya-elimuai** [comment]
@Shubham-Vishwakarma Your $ELIMU 💎 token rewards: https://etherscan.io/tx/0x3fc9bcf7cd34bb2339893ae609bb9aa34a0526c932d18072da9a02f925e5cc0f
