### ISSUE TITLE
Increase length of AudioPeerReviewEvent comment

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#1371]

**Comment by Shubham-Vishwakarma** [comment]
Is this similar to changes made in https://github.com/elimu-ai/webapp/pull/1367

**Comment by nya-elimuai** [comment]
> Is this similar to changes made in #1367

@Shubham-Vishwakarma Yes, that's right. However, note that that code change would not be complete until a corresponding DB migration script has been added as well. You can find an example of that here: https://github.com/elimu-ai/webapp/blob/master/src/main/resources/db/migration/2001201.sql
