### ISSUE TITLE
Delete allophones from Letter

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#1393]
Delete the `allophones` property from https://github.com/elimu-ai/webapp/blob/master/src/main/java/ai/elimu/model/content/Letter.java

**Comment by Shubham-Vishwakarma** [comment]
How to identify if the code is not used?

**Comment by nya-elimuai** [comment]
> How to identify if the code is not used?

@Shubham-Vishwakarma You could use an IDE like IntelliJ, NetBeans or Eclipse for example?

**Comment by Shubham-Vishwakarma** [comment]
Thanks @nya-elimuai 
I would like to give this a try

**Comment by nya-elimuai** [comment]
@Shubham-Vishwakarma Great 🙂

Do you need any assistance with getting started?

**Comment by Shubham-Vishwakarma** [comment]
I am reading the install.md to setup this
I dont have much exposure to java/maven

I will let you know if i get stuck any point

**Comment by Shubham-Vishwakarma** [comment]
home/shubham/projects/webapp/src/main/java/ai/elimu/web/content/letter/LetterCsvExportController.java:[59,46] cannot find symbol
[ERROR]   symbol:   method getAllophones()
[ERROR]   location: variable letter of type ai.elimu.model.content.Letter
[ERROR] /home/shubham/projects/webapp/src/main/java/ai/elimu/web/content/letter/LetterCsvExportController.java:[66,46] cannot find symbol
[ERROR]   symbol:   method getAllophones()
[ERROR]   location: variable letter of type ai.elimu.model.content.Letter
[ERROR] /home/shubham/projects/webapp/src/main/java/ai/elimu/util/csv/CsvContentExtractionHelper.java:[150,23] cannot find symbol
[ERROR]   symbol:   method setAllophones(java.util.List<ai.elimu.model.content.Allophone>)
[ERROR]   location: variable letter of type ai.elimu.model.content.Letter


`getAllophones` and `setAllophones` are been used in other classes?
What action is to be taken for these methods

**Comment by nya-elimuai** [comment]
> getAllophones and setAllophones are been used in other classes?

@Shubham-Vishwakarma Yes. The getter and setter would have to be deleted as well. After you delete them, you can search for occurrences of `letter.getAllophones` and `letter.setAllophones`, and then delete those lines of Java code. Also, I recommend you search for occurrences of `letter.allophones` which would show you JSP (UI) code to delete as well.

@UmenR Please correct me if I'm forgetting anything.

**Comment by nya-elimuai** [comment]
@Shubham-Vishwakarma Before closing this issue, could you please also delete the "Audio" text from the aside (right column)?: http://hin.test.elimu.ai/content/letter/edit/10

<img width="427" alt="Screen Shot 2021-08-15 at 2 59 27 PM" src="https://user-images.githubusercontent.com/15718174/129479431-29fdbcbe-0e1f-4bcd-a1f1-bfa1a4d7525f.png">

**Comment by nya-elimuai** [comment]
@Shubham-Vishwakarma Your $ELIMU 💎 token rewards: https://etherscan.io/tx/0x3fc9bcf7cd34bb2339893ae609bb9aa34a0526c932d18072da9a02f925e5cc0f
