### ISSUE TITLE
Add unit test for the `CsvContentExtractionHelper`

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#1396]
Add unit test for extracting content from the CSV files that happens on application launch. By having unit tests for this, a developer will be notified sooner when introducing breaking changes.

**Comment by vrudas** [comment]
Hi @nya-elimuai as this class contains a lot of responsibilities, is it make sense to split it into separate classes with each own usage? This approach allows for simplifying code complexity and makes it easier for covering tests.

**Comment by nya-elimuai** [comment]
> Hi @nya-elimuai as this class contains a lot of responsibilities, is it make sense to split it into separate classes with each own usage? This approach allows for simplifying code complexity and makes it easier for covering tests.

@vrudas Yes, absolutely, I think that's a great idea! Would you be interested in doing this refactoring?

**Comment by vrudas** [comment]
@nya-elimuai, have some questions before start:
- is it suitable to perform such refactoring in this issue?
- some methods(`getWordsFromCsvBackup`, `getStoryBooksFromCsvBackup`) has an extraction logic but result is ignored (by commenting code responsible for value setting into object), such comments should remain? Or can be deleted to make code more readable and easier to support/cover by tests?

**Comment by nya-elimuai** [comment]
> @nya-elimuai, have some questions before start:
> - is it suitable to perform such refactoring in this issue?
> - some methods(`getWordsFromCsvBackup`, `getStoryBooksFromCsvBackup`) has an extraction logic but result is ignored (by commenting code responsible for value setting into object), such comments should remain? Or can be deleted to make code more readable and easier to support/cover by tests?

@vrudas I would recommend this order: 

1. Add unit tests
2. Refactor the code covered by the unit tests

This way you can be sure that your refactoring does not break anything.

**Comment by nya-elimuai** [comment]
> - some methods(`getWordsFromCsvBackup`, `getStoryBooksFromCsvBackup`) has an extraction logic but result is ignored (by commenting code responsible for value setting into object), such comments should remain? Or can be deleted to make code more readable and easier to support/cover by tests?

@vrudas Yes, if you find code that has been commented out, feel free to delete it 🙂

**Comment by nya-elimuai** [comment]
@vrudas You are also welcome to join us in [Discord](https://discord.gg/9rz4XYJJDE) :-)
