### ISSUE TITLE
Skip the page for filling contributor's `motivation` during localhost development

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#1401]
To reduce app launch time during local development, pre-fill the `motivation` field at `/content/contributor/edit-motivation`.

<img width="612" alt="Screen Shot 2021-08-16 at 9 04 23 AM" src="https://user-images.githubusercontent.com/15718174/129524638-a5da0c76-2e97-4528-9ef1-a347bfefe5b5.png">

This way, the developer will be redirected to `/content` without having to go through this step. And the form will only appear in the `TEST`/`PROD` environment.

**Comment by nya-elimuai** [comment]
This feature was suggested by @Shubham-Vishwakarma 

> Please stop asking me this again and again.

**Comment by eymaal** [comment]
I would like to work on this issue if it hasn't been taken yet. 
Also do confirm if the criteria on deciding if the user is a developer is signing on using Github.

**Comment by nya-elimuai** [comment]
@eymaal You are very welcome to work on this issue 🙂

I sent an invite to your e-mail to join our GitHub organization (so that you can assign the issue to yourself).

**Comment by nya-elimuai** [comment]
Thank you, @eymaal 👍🏽 

Please close the GitHub issue and move it to the "Done" column https://github.com/elimu-ai/webapp/projects/7#card-66886366
