### ISSUE TITLE
Improve the navigation bar UI

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/webapp#1417]
When there is more content in the navigation bar, the content sometimes overflows. Improve the UX/UI so that the navigation and its content works with a variety of text lengths and screen sizes.

For an example see https://github.com/elimu-ai/webapp/issues/1362#issuecomment-907336634, reported by @cravend.

**Comment by nya-elimuai** [comment]
See @Shubham-Vishwakarma's UI suggestion at https://github.com/elimu-ai/webapp/issues/1362#issuecomment-907820176

**Comment by tnmyk** [comment]
I would like to work on this.. Can you assign it to me :)

**Comment by alexander-kuruvilla** [comment]
@nya-elimu can I work on this? 
From the current Ui I can seen that the "connect wallet" overflows and jumps out in smaller screens and the contributer name /email also jumps out.

![image](https://github.com/user-attachments/assets/732b7520-29c4-49d0-9398-4ff04db5646d)

**Comment by nya-elimu** [comment]
@alexander-kuruvilla Yes, please 👍🏽

**Comment by alexander-kuruvilla** [comment]
@nya-elimu thanks. As this is a design change I need your input on a few things, 

1. Should I change the the profile to display just the first name of the contributor as per Shubham's suggestion?
2. Should the connect account be removed or moved inside the side panel for smaller screens? Or another solution is to ditch the text in smaller screens like shown below:
![image](https://github.com/user-attachments/assets/0bf4a70f-e0e6-4163-b2c8-9426b152d910)

3. The side panel menu toggle seems to appear in smaller screens, but in the /webapp page clicking on it just dims the page and doesnt seems to bring up a menu. What is your suggestion on that?:
![image](https://github.com/user-attachments/assets/aa6ce7ec-ea23-40c1-b39f-298f50489249)

**Comment by nya-elimu** [comment]
> 1. Should I change the the profile to display just the first name of the contributor as per Shubham's suggestion?

@alexander-kuruvilla Yes, or consider using the `text-overflow` property in CSS.

**Comment by nya-elimu** [comment]
> 2\. Should the connect account be removed or moved inside the side panel for smaller screens? Or another solution is to ditch the text in smaller screens like shown below:
>     ![image](https://private-user-images.githubusercontent.com/43273583/356802464-0bf4a70f-e0e6-4163-b2c8-9426b152d910.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNDkyNDcsIm5iZiI6MTcyMzM0ODk0NywicGF0aCI6Ii80MzI3MzU4My8zNTY4MDI0NjQtMGJmNGE3MGYtZTBlNi00MTYzLWIyYzgtOTQyNmIxNTJkOTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA0MDIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NjY5YjEzMjg4MmJlZWI1MWJkMmRhZGNiOTgwNmU2OWJlNGNkYWUyOWNjNmRkYWUwMWU3MDRmM2M5YjAzOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QU_H2BPLQpAetzjznp_YKIyGuHtvJOSzfRVDKgIdUfA)

@alexander-kuruvilla I think we can move it to the side panel for smaller screens 👍🏽

**Comment by nya-elimu** [comment]
> 3\. The side panel menu toggle seems to appear in smaller screens, but in the /webapp page clicking on it just dims the page and doesnt seems to bring up a menu. What is your suggestion on that?:
>     ![image](https://private-user-images.githubusercontent.com/43273583/356802705-7cfcb2c3-4166-4011-a9b7-9ea9545169dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNDkyNDcsIm5iZiI6MTcyMzM0ODk0NywicGF0aCI6Ii80MzI3MzU4My8zNTY4MDI3MDUtN2NmY2IyYzMtNDE2Ni00MDExLWE5YjctOWVhOTU0NTE2OWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA0MDIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YjA1MjVjOGRmZjJkY2E2Y2JlZDhkM2NjNGUxZmIxMjE0ZmQ0MjVlMTUyZjRhNDI0YTViNGUzNmUzMTIxNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fy3pyOVVvqMr3NuqYV7_kJkmH7GawS999LhzfmGZo8o)

@alexander-kuruvilla I see what you mean.

<kbd>![](https://github.com/user-attachments/assets/21d2eb79-907e-4ebf-a4c9-4b9d51cf48b8)</kbd>

<kbd>![](https://github.com/user-attachments/assets/d542e9e5-944d-4001-837b-b2e09f0a8782)</kbd>

<kbd>![](https://github.com/user-attachments/assets/e159d326-4032-42d7-af23-32f1c2ff373b)</kbd>

The seems to happen when the "Sign on" link disappears. So as a solution, I suggest moving the "Connect Wallet" button into the sidebar for smaller screens. Because then there will always be content in the sidebar.

**Comment by alexander-kuruvilla** [comment]
@nya-elimu I have done the aforementioned changes. Additionally I noticed that the breadcrumb overflows out into the content in smaller screens, when the breadcrumb has a lot of elements in it.

**Comment by jo-elimu** [comment]
@alexander-kuruvilla Thank you for implementing this improvement 🙂

I did a quick test at http://hin.elimu.ai, and it looks like there is one final adjustment that needs to be made for the scenario where a content creator is _signed in_, and on a small screen, and already connected to a Web3 wallet:

![](https://github.com/user-attachments/assets/538304cd-bf56-4a6e-8530-9ecb5058b431)

![](https://github.com/user-attachments/assets/558adcb3-39cb-4272-a23c-c3e532a7c125)

![](https://github.com/user-attachments/assets/04085403-a141-40f5-ac38-0c45256be39b)

![](https://github.com/user-attachments/assets/69042323-730d-47bd-9922-230c05f9c856)

In the case where a content creator has already connected a Web3 wallet, the button should change from "Connect Wallet" to showing the same information as in the wide screen example above.

**Comment by alexander-kuruvilla** [comment]
@jo-elimu Thanks for pointing that out I'll make the changes as soon as I can. 

I would also like to know your opinion on the breadcrumbs on smaller screens. When in inner pages the breadcrumbs seem to overflow into the content div

**Comment by jo-elimu** [comment]
@alexander-kuruvilla Thanks for fixing the button in the side drawer.

One final detail: When connected loading the token balance, it works in a small screen, but not on a wide screen:

## Small Screen

![Screenshot 2024-09-11 163611](https://github.com/user-attachments/assets/7ca07d1f-2afa-4d6b-b8ae-4a0ef6eed83a)

## Wide Screen

![Screenshot 2024-09-11 163636](https://github.com/user-attachments/assets/1527993f-d57a-4792-896a-f2666ad755f6)

![Screenshot 2024-09-11 163643](https://github.com/user-attachments/assets/da261f2a-dadd-4cd2-b26c-32e74bf1c66b)

My guess would be that this is happening because both buttons have the same `#tokenBalance` ID, which should be unique per HTML element.

**Comment by alexander-kuruvilla** [comment]
> @alexander-kuruvilla Thanks for fixing the button in the side drawer.
> 
> One final detail: When connected loading the token balance, it works in a small screen, but not on a wide screen:
> 
> ## Small Screen
> ![Screenshot 2024-09-11 163611](https://private-user-images.githubusercontent.com/1451036/366408961-7ca07d1f-2afa-4d6b-b8ae-4a0ef6eed83a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNTI2ODIsIm5iZiI6MTcyNjA1MjM4MiwicGF0aCI6Ii8xNDUxMDM2LzM2NjQwODk2MS03Y2EwN2QxZi0yYWZhLTRkNmItYjhhZS00YTBlZjZlZWQ4M2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTFUMTA1OTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTNiNTY3OGI3ZThjODFiMTg5ODdkZmM5MDQxYjFiMGQ5ZjdlYzIxY2QwMjY4MjMyNDFkN2I4OGU2NTM2YWYxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5hnw1KN85UAdQD-FGPLeurxvX4KCR6eyMOhHWLHRLr0)
> 
> ## Wide Screen
> ![Screenshot 2024-09-11 163636](https://private-user-images.githubusercontent.com/1451036/366409045-1527993f-d57a-4792-896a-f2666ad755f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNTI2ODIsIm5iZiI6MTcyNjA1MjM4MiwicGF0aCI6Ii8xNDUxMDM2LzM2NjQwOTA0NS0xNTI3OTkzZi1kNTdhLTQ3OTItODk2YS1mMjY2NmFkNzU1ZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTFUMTA1OTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmU4YmMzYTgzYzJjODRmYjY2OWQwMzUwOTI5YmEzYzNhZDUwODIzMzk1NmM1ZTY2ODk1YmYyN2U0ZTg5MzU3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kE-5WlbDxAxGFDBx31kAX1igjdRQW9YzyytCveoIZGY)
> 
> ![Screenshot 2024-09-11 163643](https://private-user-images.githubusercontent.com/1451036/366409103-da261f2a-dadd-4cd2-b26c-32e74bf1c66b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNTI2ODIsIm5iZiI6MTcyNjA1MjM4MiwicGF0aCI6Ii8xNDUxMDM2LzM2NjQwOTEwMy1kYTI2MWYyYS1kYWRkLTRjZDItYjI2Yy0zMmU3NGJmMWM2NmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTFUMTA1OTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODg2NDdmMjUzNDUzYjBmMThlNDU3YzNlY2RjZjI4MTMyZmRjZTE1NjMwZDViNmMyMjg0NzI3ZGZiMjMyZjMwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ufEjS6mxBtXO9ZT3WvVRLint_Zmu4FlppaLGK6JbBf8)
> 
> My guess would be that this is happening because both buttons have the same `#tokenBalance` ID, which should be unique per HTML element.

Yes I think you are right. I'll take a look at how that can be resolved.

**Comment by jo-elimu** [comment]
@alexander-kuruvilla It works now, thank you 🙂

![](https://github.com/user-attachments/assets/f1c3ff80-68cc-4418-a0f1-006036a9d932)

close #1417

**Comment by alexander-kuruvilla** [comment]
@jo-elimu nice! Thanks!
