### ISSUE TITLE
Verify matching package name during APK upload

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#1443]
When uploading a new application version (`/admin/application-version/create?applicationId=<ID>`), check if the uploaded APK file has the expected `packageName`. If not, display an error message.

<img width="384" alt="Screen Shot 2022-01-28 at 1 05 19 PM" src="https://user-images.githubusercontent.com/15718174/151490465-64cdd29f-3c6c-475c-9d0d-0cbf4138994a.png">

---

- Relates to #1441
- Relates to #1442

**Comment by nya-elimuai** [comment]
@JairoFra Would you be able to help with the implementation of this functionality? 🙂

**Comment by JairoFra** [comment]
Hey. Sure, I'll try this weekend. 🙂
