### ISSUE TITLE
Expired SSL certificate on http://eng.elimu.ai/sign-on

### ISSUE THREAD

**Issue by hacharya** [elimu-ai/webapp#1474]
**Describe the bug**
The website isn't resolving on https due to an expired SSL certificate, in turn impacting capabilities like Google Sign-In

**To Reproduce**
1. Go to http://eng.elimu.ai/sign-on
2. Look at the browser address bar - it shows the site being "insecure"
3. Click on sign-in with Google
4. See the error in the [pop up window

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nya-elimuai** [comment]
Related to #1288

**Comment by jo-elimu** [comment]
Solved by #1288

**Comment by nya-elimuai** [comment]
@hacharya Fixed: https://eng.elimu.ai/sign-on
