### ISSUE TITLE
Replace `true`/`false` with "Yes"/"No" in the Diacritics column of a Letter

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#1522]
See example at http://eng.test.elimu.ai/content/letter/list

<img width="592" alt="Screen Shot 2022-03-15 at 4 37 54 PM" src="https://user-images.githubusercontent.com/15718174/158338784-bde8c5cf-85ab-48bf-bccf-17cfbadb1359.png">

**Comment by nya-elimuai** [comment]
@eymaal Can this issue be closed?

**Comment by eymaal** [comment]
Yes yes, the changes have reflected on the production server.
