### ISSUE TITLE
Incomplete import of ePUB from Let's Read

### ISSUE THREAD

**Issue by Bender-22** [elimu-ai/webapp#1527]
**Describe the bug**
I downloaded an ePUB from https://www.letsreadasia.org/book/377b7e63-6126-4cfe-bcee-1538d75c1b2f?bookLang=4846240843956224 and tried to import it to the website, but none of the chapters where imported: http://eng.elimu.ai/content/storybook/edit/72

**To Reproduce**
1. Go to https://www.letsreadasia.org/book/377b7e63-6126-4cfe-bcee-1538d75c1b2f?bookLang=4846240843956224
2. Click on 'Download Epub'
3. Go to http://eng.elimu.ai/content/storybook/create-from-epub and upload the file

**Expected behavior**
All storybook chapters should be imported.

**Screenshots**
![Screen Shot 2022-03-24 at 2 27 06 PM](https://user-images.githubusercontent.com/85234598/159855652-a8307e36-6b40-4e7c-abe9-b9850cd05255.png)

**Comment by nya-elimuai** [comment]
@Bender-22 The bug has been fixed. Please try importing the ePUB file again 👍🏽
