### ISSUE TITLE
Image on home page header and other static files are not loading on web app

### ISSUE THREAD

**Issue by jpatel3** [elimu-ai/webapp#1558]
**Describe the bug**
go to home page https://eng.elimu.ai/ or connect a wallet page, the image in header doesn't render an dit looks broken.

![Screen Shot 2022-05-16 at 9 41 02 AM (2)](https://user-images.githubusercontent.com/1363884/168606393-b0854c01-74d3-450b-b1c4-799be81e5257.png)

It looks like static resources are not loaded - 

![Screen Shot 2022-05-16 at 9 43 37 AM (2)](https://user-images.githubusercontent.com/1363884/168606607-9f8ce052-47cb-4532-a735-92e533a37b3e.png)

**To Reproduce**
1. Go to home page - https://eng.elimu.ai/
2. Check header broken image.
3. open console to review broken static urls.

**Desktop (please complete the following information):**
 - OS: macOS Mojave v10.14.6
 - Browser - Chrome
 - Version - 100.0.4896.127 (Official Build) (x86_64)

**Comment by nya-elimuai** [comment]
@jpatel3 Thanks for reporting this. I restarted the server. Is the problem still there?
