### ISSUE TITLE
Store Ethereum addresses in lower-case

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#1577]
To prevent duplicate accounts, store Ethereum addresses in a consistent way. Always convert to lower-case characters before storing in the database.

---

Relates to https://github.com/elimu-ai/webapp/pull/1570

**Comment by tomaszsmy** [comment]
https://github.com/elimu-ai/webapp/pull/1579

**Comment by nya-elimuai** [comment]
@tomaszsmy Your code changes have been merged and deployed to the test server. Can you connect with your Ethereum wallet at https://eng.test.elimu.ai/ to verify that it works?
