### ISSUE TITLE
Fix broken logout functionality

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#1585]
How to reproduce: 

1. Go to http://localhost:8080/webapp/sign-on
1. Sign on with a non-Web3 provider: Google/GitHub/Discord
1. Open the user drop-down, and press "Sign out"
   ![Screen Shot 2022-07-12 at 11 52 40 AM](https://user-images.githubusercontent.com/15718174/178406358-09aedfd9-e0f2-40a7-8270-f5ed14fca343.png)

Console log output:

```javascript
Killing the wallet connection undefined
web3provider.js:88 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'close')
    at disconnect (web3provider.js:88:16)
    at HTMLAnchorElement.<anonymous> (web3provider.js:107:11)
    at HTMLAnchorElement.dispatch (jquery-3.6.0.min.js:2:43064)
    at v.handle (jquery-3.6.0.min.js:2:41048)
```

**Comment by tomaszsmy** [comment]
https://github.com/elimu-ai/webapp/pull/1591
