### ISSUE TITLE
Error when editing storybooks: difflib is not defined

### ISSUE THREAD

**Issue by jo-elimu** [elimu-ai/webapp#1632]
**Describe the bug**
The paragraph text diff is not appearing in a storybook's contribution events.

**To Reproduce**
1. Go to http://localhost:8080/webapp/content/storybook/list
2. Click on any storybook
3. Edit any paragraph
4. Scroll down to 'Contributions 👩🏽‍💻'
5. See error in browser console: 
  ```
  jquery-3.6.0.min.js:2 Uncaught ReferenceError: difflib is not defined
    at HTMLDocument.<anonymous> (1:627:47)
    at e (jquery-3.6.0.min.js:2:30038)
    at t (jquery-3.6.0.min.js:2:30340)
  ```

**Expected behavior**
Should see the text diff of the previous and new paragraph.

**Comment by tomaszsmy** [comment]
#1643
