### ISSUE TITLE
Error while signing on using Discord if no avatar

### ISSUE THREAD

**Issue by venkatesh2k3** [elimu-ai/webapp#1649]
**Description:**

I am encountering an issue in an application when a user signs on using Discord and does not have an avatar. The application throws the following error:
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.json.JSONException: JSONObject["avatar"] is not a string.

**Steps to Reproduce:**
Attempt to sign on using a Discord account that does not have an avatar.
The error occurs during the request processing.

**Expected Behavior:**
The sign-on process should handle the absence of an avatar gracefully without throwing an exception.

**Actual Behavior:**
The request fails with the following error:
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.json.JSONException: JSONObject["avatar"] is not a string.

**Screenshots:**
![Screenshot 2024-06-30 123102](https://github.com/elimu-ai/webapp/assets/137500548/c8045b4f-0c6d-4f9b-859a-f3a1489a0b5a)

**Comment by jo-elimu** [comment]
Related file: `SignOnControllerDiscord.java`

**Comment by jo-elimu** [comment]
The current version of the code is expecting this JSON response format:
```json
{"id":"***","username":"***","avatar":"b49fa80a9b522a4f46128dc093ca26ea"}
```

**Comment by jo-elimu** [comment]
@venkatesh2k3 What does the JSON response look like when the error occurs?

**Comment by venkatesh2k3** [comment]
like null or a JSON object

**Comment by jo-elimu** [comment]
> like null or a JSON object

`"avatar":null`?

**Comment by jo-elimu** [comment]
@venkatesh2k3 If you share a sample of what the JSON response looks like when the error occurs, it would probably be easier to solve this issue.

**Comment by venkatesh2k3** [comment]
![Screenshot 2024-06-30 164240](https://github.com/elimu-ai/webapp/assets/137500548/a397127d-45bc-4e18-930d-2894eee8f0ca)
@jo-elimu Yes, "avatar":null

**Comment by jo-elimu** [comment]
@venkatesh2k3 Got it, thanks. Then it can probably be solved with by adding a null check?
```
jsonObject.isNull("avatar")
```

**Comment by venkatesh2k3** [comment]
@jo-elimu Still needs to be checked for type and blank, it would be solved by the code below.
 `(!jsonObject.isNull("avatar") && jsonObject.get("avatar") instanceof String && !StringUtils.isBlank(jsonObject.getString("avatar")))`

**Comment by venkatesh2k3** [comment]
@jo-elimu It works
