### ISSUE TITLE
Rename from `deviceId` to `androidId`

### ISSUE THREAD

**Issue by jo-elimu** [elimu-ai/webapp#1672]
To make the code in the `Device` entity consistent with the code in the Analytics app, rename from `Device#deviceId` to `Device#androidId`.

**Comment by alexander-kuruvilla** [comment]
Hi @jo-elimu I would like to take this up. So Im guessing this would require a database migration script as well to change the deviceid attribute to androidid?

**Comment by jo-elimu** [comment]
> Hi @jo-elimu I would like to take this up. So Im guessing this would require a database migration script as well to change the deviceid attribute to androidid?

Thank you, @alexander-kuruvilla. Yes, that's correct. You can find the current DB table structure in the JPA schems export file.

**Comment by alexander-kuruvilla** [comment]
Hi @jo-elimu, in the JPA schema export file in addition to the Device table, I also see that a unique key is added to the deviceId.

`    alter table Device 
       add constraint UK_ktkbd0xm3q2nddw1xxtdaxjy7 unique (deviceId);`

 Should drop the unique key and re-add it for the androidId in the migration script?

**Comment by alexander-kuruvilla** [comment]
Alright @jo-elimu , I'll hold off on altering the constraint. After running on local the unique constraint value in the jpa schema export seems to change as well, so I guess it would add the constraints automagically.

**Comment by jo-elimu** [comment]
@alexander-kuruvilla The migration script could not be executed:

```java
[HIN] 01:32:29.020 [main] INFO  ai.elimu.util.db.DbMigrationHelper - Looking up file "db/migration/2004020.sql"...
[HIN] 01:32:29.020 [main] INFO  ai.elimu.util.db.DbMigrationHelper - Migration script found for version 2004020
[HIN] 01:32:29.021 [main] INFO  ai.elimu.util.db.DbMigrationHelper - Executing sql: ALTER TABLE `Device` DROP COLUMN `deviceId`;
[HIN] 01:32:29.045 [main] INFO  ai.elimu.util.db.DbMigrationHelper - Executing sql: ALTER TABLE `Device` CHANGE `deviceId` `androidId` VARCHAR(255);
[HIN] 01:32:29.047 [main] WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 1054, SQLState: 42S22
[HIN] 01:32:29.047 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Unknown column 'deviceId' in 'Device'
[HIN] 01:32:29.059 [main] ERROR ai.elimu.web.servlet.CustomDispatcherServlet - Context initialization failed
org.springframework.dao.InvalidDataAccessResourceUsageException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute statement
```

So I think we just need to replace DROP COLUMN `deviceId` with DROP COLUMN `androidId` and run the migration script again. Sorry, I missed that during the PR review.

**Comment by alexander-kuruvilla** [comment]
Oh ok, so @jo-elimu is this what you meant?

`ALTER TABLE `Device` DROP COLUMN `androidId`;
ALTER TABLE `Device` CHANGE `deviceId` `androidId` VARCHAR(255);`

**Comment by jo-elimu** [comment]
@alexander-kuruvilla Yes 👍

Would you mind creating a pull request for that change?

**Comment by alexander-kuruvilla** [comment]
@jo-elimu Thanks for that. Sorry, I was a bit busy and didn't check my mail.

**Comment by jo-elimu** [comment]
> @jo-elimu Thanks for that. Sorry, I was a bit busy and didn't check my mail.

@alexander-kuruvilla No worries. Since the `deviceId` column was dropped earlier, I manually restored it with `ALTER TABLE `Device` ADD COLUMN `deviceId` VARCHAR(255);` before running the updated migration script again.

And we haven't started storing any data in the `Device` table yet, so it's not a problem that the wrong column was dropped.
