### ISSUE TITLE
Migrate from JUnit 4 to JUnit 5

### ISSUE THREAD

**Issue by jo-elimu** [elimu-ai/webapp#1679]
https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4

**Comment by venkatesh2k3** [comment]
By adding a dependency, it would be resolved right?

**Comment by jo-elimu** [comment]
> By adding a dependency, it would be resolved right?

@venkatesh2k3 It's probably not that simple, because we have several tests that are tied to JUnit 4 with the `@RunWith(SpringJUnit4ClassRunner.class)` annotation. So the migration will probably require some refactoring work.
