### ISSUE TITLE
Document steps for running regression tests

### ISSUE THREAD

**Issue by jo-elimu** [elimu-ai/webapp#1767]
See `pom.xml` profiles: `regression-testing-rest`, `regression-testing-ui`.

Write a new `TEST.md` document.

**Comment by sanjanaynvsdl** [comment]
Hey @jo-elimu ,
I would like work on this issue can you please assign this to me!

**Comment by jo-elimu** [comment]
> I would like work on this issue can you please assign this to me!

@sanjanaynvsdl Now that you are a member of the GitHub organization, feel free to self-assign yourself issues 🙂

**Comment by charanbhatia** [comment]
@jo-elimu can I get to know how to be a member of this organization ?

**Comment by jo-elimu** [comment]
@charanbhatia If you have received an invite to join the GitHub organization, I think you can go to https://github.com/orgs/elimu-ai/people to accept it.
