### ISSUE TITLE
Display Hindi resources in similar format as the General resources

### ISSUE THREAD

**Issue by jo-elimu** [elimu-ai/webapp#1779]
Small UX/UI improvement.

At `/content/letter/edit/<ID>`, adjust the layout of the "Hindi resources" list so that the items are shown in a bullet list (as in the "General resources" list below it):

<kbd>![](https://github.com/user-attachments/assets/7956c852-a839-4681-af9a-e1037ff5b803)</kbd>

And make similar adjustments at `/content/letter/create`.

**Comment by alexander-kuruvilla** [comment]
Hi @jo-elimu when does this section appear? When I hit edit letter I am only able to view the "general resources" section

**Comment by venkatesh2k3** [comment]
@jo-elimu That section did not appear among the general resources above.

**Comment by jo-elimu** [comment]
@alexander-kuruvilla @venkatesh2k3 Sorry, forgot to mention that you need to change the language from English to Hindi in `config.properties`.

**Comment by venkatesh2k3** [comment]
@jo-elimu we need to change `content.language=ENG` to what?

**Comment by jo-elimu** [comment]
https://github.com/elimu-ai/webapp/pull/1781
