### ISSUE TITLE
Move machine learning code into utils class

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/webapp#1825]
For better separation of concerns, move the code for calling the machine learning model from `StoryBookCreateFromEPubController` into its own utils class in a new `ai.elimu.util.ml` package. Also move the PMML file to `src/main/resources/ai/elimu/util/ml`, and add unit tests for covering the code in the new utils class.

---

- Depends on #1821
- Relates to #1920

**Comment by Aryant-Tripathi** [comment]
@nya-elimu May I be allowed to pick this up?

**Comment by nya-elimu** [comment]
> @nya-elimu May I be allowed to pick this up?
> 

@Aryant-Tripathi Please do! 🙂

**Comment by Aryant-Tripathi** [comment]
Hey, @nya-elimu Method `handleSubmit() `contains I guess a legacy code of around 400 lines and involve multiple things in a single method. Do I need to refactor the method and try to extract some independent pieces which we can use in util file OR do i need to put method `List<File> unzipFiles(byte[] ePubBytes, String originalFilename) into utility file only.`

I guess refactoring the method into some smaller methods, and extracting things into utility files and fetching some data by making them environment variables would be helpful, but it seems it will take too much of effort and we need to create test cases for the same also.

**Comment by jo-elimu** [comment]
@Aryant-Tripathi I think the task here would be to only move the code related to the machine learning model inference, i.e. the [`predictReadingLevel`](https://github.com/elimu-ai/webapp/blob/main/src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java#L544) method.
