### ISSUE TITLE
Replace broken link pointing to Tagalog dictionary

### ISSUE THREAD

**Issue by jo-elimu** [elimu-ai/webapp#1841]
Replace https://www.tagaloglessons.com/words/isang.php with https://www.tagalog.com/dictionary/isang (just using the word "isang" as an example here)

http://tgl.elimu.ai/content/word/edit/10

![image](https://github.com/user-attachments/assets/d5c4baf1-79d1-4225-84c7-8e995234e2ca)

**Comment by Rafael-Floriano** [comment]
Hi @jo-elimu I can get this task?
