### ISSUE TITLE
Remove `/contributions/most-recent`

### ISSUE THREAD

**Issue by jo-elimu** [elimu-ai/webapp#1912]
## Description

Remove all code related to the URL `/contributions/most-recent`, i.e. the Controller, JSP, CSS, links in from other pages, etc.

## Why?

* To reduce complexity.

**Comment by Aryant-Tripathi** [comment]
@jo-elimu , may I allowed to pick this task ?

**Comment by jo-elimu** [comment]
@Aryant-Tripathi Please do 🙂

**Comment by Aryant-Tripathi** [comment]
@jo-elimu If possible may you be able to mark/tag PR as hacktoberfest-accepted / hacktoberfest label. It will help me in contributing a PR in hacktoberfest.

**Comment by jo-elimu** [comment]
@Aryant-Tripathi Done 👍

**Comment by Aryant-Tripathi** [comment]
I am sorry @jo-elimu , for this little change I am asking you to do these things, 

but I need label **hacktoberfest-accepted** on the PR.

This is what hactoberfest says:

**Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers need to add the hacktoberfest topic to the repository, or add the hacktoberfest-accepted label to your PR.
For more information about how exactly we validate PRs for contributors, check the details on our participation page.**

**Comment by jo-elimu** [comment]
> Maintainers need to add the hacktoberfest topic to the repository, or add the hacktoberfest-accepted label to your PR.

@Aryant-Tripathi I've added the `hacktoberfest` topic to the repository: https://github.com/elimu-ai/webapp
