### ISSUE TITLE
Do not allow words with spaces

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#420]
Example: http://eng.elimu.ai/content/word/edit/700

<img width="185" alt="Screen Shot 2021-08-04 at 1 36 53 PM" src="https://user-images.githubusercontent.com/15718174/128174325-9f552c30-ba3b-4719-a053-b0fe94c84fad.png">

**Comment by jo-elimu** [comment]
Another example: http://eng.elimu.ai/content/word/edit/164
