### ISSUE TITLE
The repo is not possible to check out

### ISSUE THREAD

**Issue by aschworer** [elimu-ai/webapp#570]
The problem is the file `webapp/src/main/webapp/static/audio/sw/sampa_b_>.wav` and the character `>`
The file needs to be renamed.
@jo-elimuai please give the new name, also, can there be any bugs after renaming this?

**Comment by jo-elimuai** [comment]
See `AllophoneListController`, which auto-generates test data to be used during development.

To verify that it still works after changing, start the webapp on your local machine, and go to 
`/content/allophone/list`

**Comment by aschworer** [comment]
I'll rename it to sampa_b__.wav and see if it works

**Comment by aschworer** [comment]
Same happens on Ubuntu

**Comment by elimuai** [comment]
@aschworer What does "not possible to checkout" mean? Is it not possible to download the files from GitHub by clicking the "clone" button?

**Comment by aschworer** [comment]
@elimuai yes
