### ISSUE TITLE
Remove unused variables & redundant declarations (code enhacement)

### ISSUE THREAD

**Issue by aschworer** [elimu-ai/webapp#571]
Small code fixes to make it look better (i.e. code styling, minor code issues, etc.)

**Comment by jo-elimuai** [comment]
What type of code cleaning is required? Can you describe this issue more specifically so that any developer will understand how to implement the changes?

**Comment by aschworer** [comment]
@jo-elimuai 

**What has been done in [571-small_code_fixes branch](https://github.com/elimu-ai/webapp/tree/571-small_code_fixes) :**

- removed unused variables & redundant declarations
- upgraded few constructions to use java 5 (i.e. loops vs. for-each)
- upgraded few constructions to use java 7 (i.e. try-catch blocks)
- upgraded few constructions to use java 8 capabilities (i.e. lambdas, `.removeIf()`)
- replaces few `Collections.sort()` with `list.sort()`
- replaced access to static variable from object to class levels (i.e. `return soundType.VOWEL;` replaced with `return SoundType.VOWEL;`)
- replaced `Arrays.asList()` with only 1 argument with `Collections.singletonList()` for better performance
- string concatenations in a loop (which are hard on space and performance) replaced with `StringBuilder`
- removed identical catch blocks (if exception handling is same)



**Still to be done**

I will create separate issues for this, so that this merge request is not too big

- remove duplicated code in Controllers & Syllable/Letter FrequencyHelpers, Schedulers, 
- remove usage of deprecated methods & APIs, for example:
  `URLEncoder.encode(contributor.getLastName());`
  should be replace everywhere with 
  `URLEncoder.encode(contributor.getLastName(), "UTF-8");`

  or
  
  `org.apache.commons.validator.EmailValidator#isValid ` - EmailValidator is deprecated

  or in jpa-persistence.xml `HibernatePersistence` is deprecated

- DiamoExplicit type arguments can be replaces with empty diamond operator when declaring some generics, for example:

  `List<HttpMessageConverter<?>> messageConverters = new ArrayList<HttpMessageConverter<?>>();`

  starting Java 7 can be replaced with

  `List<HttpMessageConverter<?>> messageConverters = new ArrayList<>();`

  This also can be left as is, for better code readability. I guess it's up to you ;)

**Comment by aschworer** [comment]
I'm going to split this issue into several smaller, to allow smaller pull requests.
Starting with the first in the list: "remove unused variables & redundant declarations" (renaming the issue)
