### ISSUE TITLE
Facilitate usage with Docker

### ISSUE THREAD

**Issue by jo-elimu** [elimu-ai/webapp#598]

**Comment by jo-elimuai** [comment]
See https://github.com/elimu-ai/webapp/tree/master/src/main/resources for the different environment settings the Docker containers should support.

**Comment by syntrydy** [comment]
Step to move the web application to docker:
   

- Make some search about the best pratices to use when moving web application to docker
-Do it manually first(generated the web app jar and use docker command to build a new image container the web application and the database,test the container to make sure it is ok)
-Automated the above steps.
