### ISSUE TITLE
Remove duplicate JSON objects from response [4-8h]

### ISSUE THREAD

**Issue by jo-elimuai** [elimu-ai/webapp#615]
Remove duplicate `application` information from JSON response when calling https://github.com/elimu-ai/webapp/blob/master/REST_API_REFERENCE.md#read-applications

![capture](https://user-images.githubusercontent.com/1451036/33229644-d2836ad4-d1d2-11e7-8fc3-afece542a53b.png)

Reported by @tuancoltech

**Comment by nya-elimuai** [comment]
This was fixed in `v2`
