### ISSUE TITLE
Google login redirects to wrong domain

### ISSUE THREAD

**Issue by jo-elimuai** [elimu-ai/webapp#633]
> The login didn't work fine for me in Google Chrome and while loggin in into the gmail account there was a message, that after login I will be redirected to the test.elimu.ai, so I just tried this address.

**Comment by JakubRuzicka** [comment]
I can't reproduce this bug. Can you write more details how to reproduce it please?

**Comment by nya-elimuai** [comment]
Was fixed in #699
