### ISSUE TITLE
Add educational content: Hindi

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/webapp#743]
See https://github.com/elimu-ai/wiki/projects/2

- [x] Allophones
- [x] Letters
- [ ] Storybooks
- [ ] Words
- [ ] Numbers
- [ ] Syllables
- [ ] Audios
- [ ] Images
- [ ] Videos

**Comment by nya-elimuai** [comment]
For Allophones, seee https://github.com/marytts/marytts-lang-hi/blob/master/lib/modules/hi/lexicon/allophones.hi.xml
