### ISSUE TITLE
Add educational content: Bengali

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/webapp#774]
- [x] Storybooks
- [x] Allophones
- [x] Letters
- [x] Words
- [x] Numbers
- [ ] Syllables
- [x] Emojis
- [ ] Images
- [ ] Audios
- [ ] Videos

Depends on #714

**Comment by nya-elimuai** [comment]
See https://en.wikibooks.org/wiki/Bengali/Sounds
