### ISSUE TITLE
Add REST API for crowdsourcing audio recordings

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#952]
- [x] Create new audio recordings: Word
- [x] Peer review existing audio recordings: Word

See corresponding peer review functionality on the website: http://eng.test.elimu.ai/content/multimedia/audio/list

<img width="627" alt="Screen Shot 2021-05-06 at 3 58 00 PM" src="https://user-images.githubusercontent.com/15718174/117310806-4d45b300-ae8c-11eb-9655-62e0b575c15f.png">
<img width="623" alt="Screen Shot 2021-05-06 at 3 58 06 PM" src="https://user-images.githubusercontent.com/15718174/117310809-4e76e000-ae8c-11eb-945f-c294c152d860.png">
<img width="620" alt="Screen Shot 2021-05-06 at 3 58 19 PM" src="https://user-images.githubusercontent.com/15718174/117310812-4e76e000-ae8c-11eb-97ce-3ef4ae5e480d.png">

---

- Depends on #953 and https://github.com/elimu-ai/model/issues/197 and https://github.com/elimu-ai/model/issues/199
- Relates to #1227
- Depends on https://github.com/elimu-ai/model/projects/7#card-61559890

**Comment by nya-elimuai** [comment]
@So-Somila See screenshots above. We'll implement a similar functionality in the crowdsource app. Does this seem like a good user experience to you?

**Comment by So-Somila** [comment]
> @So-Somila See screenshots above. We'll implement a similar peer review functionality in the crowdsource app as on the website. Does this seem like a good user experience to you?

@nya-elimuai Yes, I like this. It's simple and clear. Are we also going to have a peer review of the words (i.e is the person pronouncing it correctly)?
