### ISSUE TITLE
Hindi letter not rendering correctly

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#981]
See https://storyweaver.org.in/stories/30045-jaaduee-gutaka

<img width="163" alt="Screenshot 2020-07-13 at 08 30 21" src="https://user-images.githubusercontent.com/15718174/87260218-1d838400-c4e3-11ea-91aa-4070aa2509fc.png">

<img width="382" alt="Screen Shot 2020-10-15 at 7 49 46 PM" src="https://user-images.githubusercontent.com/15718174/96174476-07e28800-0f32-11eb-96c1-fe15853da3be.png">

The letter in the storybook title renders as 'र्इ'. See http://hin.elimu.ai/content/storybook/edit/55

Is this a problem with StoryWeaver or with elimu.ai?

---

Steps to reproduce:
1. Run the webapp locally: https://github.com/elimu-ai/webapp/blob/master/INSTALL.md
2. Change the default language from English to Hindi by modifying [`config.properties`](https://github.com/elimu-ai/webapp/blob/master/src/main/resources/config.properties#L15)
3. Download the storybook (APK file) from https://storyweaver.org.in/stories/30045-jaaduee-gutaka
4. Go to http://localhost:8080/webapp/content/storybook/list and press "Upload ePUB file"
    <img width="295" alt="Screen Shot 2020-10-15 at 8 00 50 PM" src="https://user-images.githubusercontent.com/15718174/96168529-8be44200-0f29-11eb-8309-46e3402d598f.png">

### Findings :
The letter is not rendering on Chrome but it reflects on Safari hence concluding this as a browser issue. 
Moreover, this word is perfect on elmui.ai android app which is the main tool for the end-user, thanks to @nya-elimuai for confirming. 

**Note**: Here are the two words which have same letter `ई` in different formats in epub. One is rendered correctly on Chrome Web but not the other, below are screenshots to show the difference. 
Screenshot of Epub Downlaod from StoryWeaver:
<img width="531" alt="Screen Shot 2020-10-30 at 8 07 50 PM" src="https://user-images.githubusercontent.com/19628734/97769978-799f0200-1aec-11eb-97f4-31588d2935b8.png">

Screenshot of Webapp:
![Screen Shot 2020-10-30 at 7 58 17 PM](https://user-images.githubusercontent.com/19628734/97769986-8a4f7800-1aec-11eb-9115-931a85445853.png)

**Comment by Keerthi4308** [comment]
Hello @nya-elimuai , I will pick this task, you can go ahead assign it to me.

**Comment by nya-elimuai** [comment]
@Keerthi4308 I also uploaded the ePUB at https://elimu-ai.slack.com/archives/C01BBVDAUP9/p1602788387003000

**Comment by Keerthi4308** [comment]
Upon investigation, we marking this issue as `wontfix` for more details please look at the Findings sec in the issue description.

**Comment by Keerthi4308** [comment]
Upon investigation, we marking this issue as `wontfix` for more details please look at the Findings sec in the issue description.
